name: salvation_ministries_library
description: Salvation ministries digital library

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"






dependencies:
  flutter:
    sdk: flutter
  firebase_auth: 0.7.0
  firebase_storage: 1.0.4
  progress_dialog: 1.1.0
  fluttertoast: 3.0.4
  firebase_database: 1.0.5
  image_picker: 0.4.12+1
  shared_preferences: 0.4.3
  url_launcher: 5.0.2
  video_player: ^0.10.1
  webview_flutter: 0.2.0
  android_intent: 0.2.1
  connectivity: 0.3.2
  font_awesome_flutter: 8.4.0
  flutter_country_picker: 0.1.3
  country_code_picker: 1.1.5
  date_format: 1.0.6
  clippy_flutter: 1.1.0
  rflutter_alert: 1.0.2
  giffy_dialog: 1.3.0
  flutter_credit_card: 0.1.1
  http: ^0.12.0+2
  xml: ^3.3.0
  audioplayer: ^0.5.2
  path_provider: ^1.1.0
  flutter_webview_plugin: ^0.3.5
  flutter_simple_video_player: ^0.0.9
  flutter_pdf_viewer: ^0.4.1
  flutter_launcher_icons: ^0.7.2
  in_app_purchase: ^0.2.1+3
  iap: ^0.1.0






  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/log.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/image/teacher.png
      - assets/image/imgone.png
      - assets/image/imgtwo.png
      - assets/image/imgthree.png
      - assets/image/background.png
      - assets/image/birth.png
      - assets/image/business.png
      - assets/image/communion.png
      - assets/image/event.png
      - assets/image/excellence.png
      - assets/image/faith.png
      - assets/image/family.png
      - assets/image/fivenight.JPG
      - assets/image/healing.png
      - assets/image/holyspirit.png
      - assets/image/power.png
      - assets/image/praise.png
      - assets/image/prayer.png
      - assets/image/soul.png
      - assets/image/success.png
      - assets/image/vengence.png
      - assets/image/wisdom.png
      - assets/image/word.png
      - assets/image/bg.png
      - assets/image/log.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#  fonts:
#     - family: Schyler
#       fonts:
#         - asset: fonts/Schyler-Regular.ttf
#         - asset: fonts/Schyler-Italic.ttf
#           style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: blacksword
      fonts:
        - asset: fonts/blacksword.otf
          style: italic
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
